spring:
  config:
    activate:
      on-profile:
        active: development
---
spring:
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost/dev
    username: dbuser
    password: dbpass
  config:
    activate:
      on-profile: development
---
spring:
  jpa:
    show_sql: false
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  config:
    activate:
      on-profile: test